### ISSUE TITLE
Extends currently don't work for many utilities

### ISSUE THREAD

**Issue by daveredfern** [getchopchop/chopchop#100]
We're relying on wildcard class selectors for many classes in utilities that have loops. We need to change them to something like this so extends do work:

``` css
[class*="u-container"] {
    margin-left: auto;
    margin-right: auto;
    width: 96%;
}

@each $key, $value in $containers {
    .u-container-#{$key} {
        max-width: $value;
    }
    %u-container-#{$key} {
        margin-left: auto;
        margin-right: auto;
        max-width: $value;
        width: 96%;
    }
}
```
