### ISSUE TITLE
Improve flags

### ISSUE THREAD

**Issue by daveredfern** [getchopchop/chopchop#136]
Add grows and shrinks to flags. Improve the demos too.

```scss
.flag {
    @include flex;
    @include align-items(center);
    @include justify-content(space-between);

    &--gutter {
        @include grid-gutter-x;
    }

    > *:first-child {
        flex-shrink: 0;
    }

    > *:last-child {
        flex-grow: 1;
    }

    &--reverse {
        flex-direction: row-reverse;
    }
}
```
