### ISSUE TITLE
Rework flags

### ISSUE THREAD

**Issue by daveredfern** [getchopchop/chopchop#154]
Rework flags

```css
// =============================================
// Flag
// =============================================

.u-flag {
    @include flex;
}


// =============================================
// Flag with gutter
// =============================================

.u-flag--gutter {
    @include grid-gutter-x;
}


// =============================================
// Flag centered
// =============================================

.u-flag--center {
    @include align-items(center);
}


// =============================================
// Flag split
// =============================================

.u-flag--split {
    @include justify-content(space-between);
}


// =============================================
// Flag reversed
// =============================================

.u-flag--reverse {
    @include flex-direction(row-reverse);
}


// =============================================
// Flag stretched
// =============================================

.u-flag--stretch {
    > *:first-child {
        flex-grow: 1;
    }
    > *:last-child {
        flex-shrink: 0;
    }
}
```
