### ISSUE TITLE
Add separator classes

### ISSUE THREAD

**Issue by daveredfern** [getchopchop/chopchop#155]
```css
// =============================================
// Separator
// =============================================

.u-separator {
    border: 1px solid color(grey,light);
}

.u-separator-top {
    border-top: 1px solid color(grey,light);
}

.u-separator-bottom {
    border-bottom: 1px solid color(grey,light);
}

.u-separator-left {
    border-left: 1px solid color(grey,light);
}

.u-separator-right {
    border-right: 1px solid color(grey,light);
}
```
