### ISSUE TITLE
Remove margin bottom on last child inside grid columns

### ISSUE THREAD

**Issue by daveredfern** [getchopchop/chopchop#17]
Add the following the grid items to zero the margin on the last item. This will ensure the spacing between the grid items is correct and the margin of elements inside each column doesn't increase it.

``` css
.grid > * *:last-child {
margin-bottom:0;
}
```

This will keep the margin by default on patterns so they space correctly when not used inside a grid.
