### ISSUE TITLE
Adding custom colours such as gradients breaks presentation

### ISSUE THREAD

**Issue by daveredfern** [getchopchop/chopchop#182]
![image](https://cloud.githubusercontent.com/assets/183473/22776431/85a9a02a-eea7-11e6-8946-359dda546ccc.png)

PHP error when adding something like this:

```scss
.u-fill-gradient-light,
%u-fill-gradient-light {
    background-color: color(neutral, lightest);
    background: linear-gradient(to top, color(neutral, lightest) 0%,#f9f9f9 100%);
}
```
