### ISSUE TITLE
Full height utility class

### ISSUE THREAD

**Issue by daveredfern** [getchopchop/chopchop#44]
This pattern keeps cropping up. It's where two divs need to stretch to be the full height. Common case is inside grid columns.

![image](https://cloud.githubusercontent.com/assets/183473/17054142/757396a0-4ffd-11e6-9a5f-221a55fb5c52.png)

I suggest a `.u-full-height` utility that sets flex onto internal items to stretch them correctly. This is the css I have been using:

``` css
.u-full-height {
        display: flex;
        flex-flow: wrap;

        > * {
            width: 100%;
        }
}
```
